# fly.toml app configuration file generated for swift-af on 2023-11-25T01:12:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "swift-af"
primary_region = "iad"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
